-- ============================================================
-- CEIT 435 – LearnCSS PostgreSQL Database
-- ============================================================
-- This file contains:
-- 1) Database sanity test
-- 2) Core table definitions
-- 3) Topic & quiz seed data
-- 4) Example test flow (learner → quiz → progress → certificate)
--
-- IMPORTANT FOR TEAM:
-- - Do NOT blindly re-run everything in production
-- - Sections are clearly labeled as SETUP / SEED / TEST
-- ============================================================



-- ============================================================
-- [TEST] Simple sanity check to confirm UUID + DB is working
-- This table is NOT used in the project logic
-- Can be safely deleted later
-- ============================================================
BEGIN;

CREATE TABLE IF NOT EXISTS test_ok (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid()
);

COMMIT;



-- ============================================================
-- [SETUP] Start of actual project schema
-- Everything below is REQUIRED for the system to work
-- ============================================================
BEGIN;



-- ============================================================
-- LEARNERS
-- ------------------------------------------------------------
-- Represents users of the system.
-- session_id is generated by frontend (UUID in cookie/localStorage)
-- No login is required for the project.
-- ============================================================
CREATE TABLE IF NOT EXISTS learners (
  learner_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID UNIQUE,
  user_name TEXT,
  email TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  last_seen_at TIMESTAMPTZ
);



-- ============================================================
-- TOPICS (LESSONS)
-- ------------------------------------------------------------
-- Each topic corresponds to one CSS lesson in the frontend
-- topic_key MUST match frontend lesson identifiers
-- ============================================================
CREATE TABLE IF NOT EXISTS topics (
  topic_key TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  order_no INT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE
);



-- ============================================================
-- QUIZZES
-- ------------------------------------------------------------
-- One quiz per topic
-- passing_score_percent controls completion logic
-- ============================================================
CREATE TABLE IF NOT EXISTS quizzes (
  quiz_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  topic_key TEXT NOT NULL REFERENCES topics(topic_key),
  title TEXT NOT NULL,
  passing_score_percent NUMERIC(5,2) DEFAULT 70,
  is_active BOOLEAN DEFAULT TRUE
);



-- ============================================================
-- QUIZ QUESTIONS
-- ------------------------------------------------------------
-- Each quiz has multiple questions
-- ============================================================
CREATE TABLE IF NOT EXISTS quiz_questions (
  question_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quiz_id UUID NOT NULL REFERENCES quizzes(quiz_id),
  question_text TEXT NOT NULL,
  explanation TEXT,
  order_no INT NOT NULL
);



-- ============================================================
-- QUIZ OPTIONS
-- ------------------------------------------------------------
-- Multiple-choice answers for each question
-- is_correct = TRUE marks the correct option
-- ============================================================
CREATE TABLE IF NOT EXISTS quiz_options (
  option_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id UUID NOT NULL REFERENCES quiz_questions(question_id),
  option_text TEXT NOT NULL,
  is_correct BOOLEAN DEFAULT FALSE,
  order_no INT NOT NULL
);



-- ============================================================
-- QUIZ ATTEMPTS
-- ------------------------------------------------------------
-- Each time a learner takes a quiz, one row is inserted
-- ============================================================
CREATE TABLE IF NOT EXISTS quiz_attempts (
  attempt_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID NOT NULL REFERENCES learners(learner_id),
  quiz_id UUID NOT NULL REFERENCES quizzes(quiz_id),
  started_at TIMESTAMPTZ DEFAULT now(),
  submitted_at TIMESTAMPTZ,
  score_percent NUMERIC(5,2),
  is_passed BOOLEAN
);



-- ============================================================
-- QUIZ ANSWERS
-- ------------------------------------------------------------
-- Stores selected answers per question per attempt
-- ============================================================
CREATE TABLE IF NOT EXISTS quiz_answers (
  answer_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  attempt_id UUID NOT NULL REFERENCES quiz_attempts(attempt_id),
  question_id UUID NOT NULL REFERENCES quiz_questions(question_id),
  chosen_option_id UUID REFERENCES quiz_options(option_id),
  answered_at TIMESTAMPTZ DEFAULT now()
);



-- ============================================================
-- TOPIC PROGRESS
-- ------------------------------------------------------------
-- Tracks best score and completion per learner per topic
-- This table powers progress bars and certification logic
-- ============================================================
CREATE TABLE IF NOT EXISTS topic_progress (
  learner_id UUID REFERENCES learners(learner_id),
  topic_key TEXT REFERENCES topics(topic_key),
  best_score_percent NUMERIC(5,2) DEFAULT 0,
  is_completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  PRIMARY KEY (learner_id, topic_key)
);



-- ============================================================
-- CERTIFICATES
-- ------------------------------------------------------------
-- Issued when ALL active topics are completed
-- completed_topics stores a snapshot of completed topic keys
-- ============================================================
CREATE TABLE IF NOT EXISTS certificates (
  certificate_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID REFERENCES learners(learner_id),
  certificate_code TEXT UNIQUE,
  issued_at TIMESTAMPTZ DEFAULT now(),
  completed_topics JSONB
);



COMMIT;



-- ============================================================
-- [DEBUG / VERIFICATION]
-- Lists all created tables
-- ============================================================
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;



-- ============================================================
-- [SEED DATA] Topics (RUN ONCE)
-- ------------------------------------------------------------
-- Matches frontend lesson structure
-- ============================================================
INSERT INTO topics (topic_key, title, category, order_no) VALUES
('intro',     'Introduction to CSS',  'Basics', 1),
('selectors', 'CSS Selectors',        'Basics', 2),
('colors',    'Colors & Backgrounds', 'Basics', 3),
('boxmodel',  'CSS Box Model',        'Layout', 4),
('flexbox',   'Flexbox Layout',       'Layout', 5),
('grid',      'CSS Grid Layout',      'Layout', 6)
ON CONFLICT (topic_key) DO NOTHING;



-- View topics
SELECT * FROM topics ORDER BY order_no;



-- ============================================================
-- Enforce ONE quiz per topic at database level
-- ============================================================
ALTER TABLE quizzes
ADD CONSTRAINT uq_quiz_per_topic UNIQUE (topic_key);



-- ============================================================
-- [SEED DATA] Quizzes (RUN ONCE)
-- ============================================================
INSERT INTO quizzes (topic_key, title, passing_score_percent) VALUES
('intro',     'Intro Quiz',     70),
('selectors', 'Selectors Quiz', 70),
('colors',    'Colors Quiz',    70),
('boxmodel',  'Box Model Quiz', 70),
('flexbox',   'Flexbox Quiz',   70),
('grid',      'Grid Quiz',      70)
ON CONFLICT (topic_key) DO NOTHING;



-- View quizzes
SELECT topic_key, title, passing_score_percent
FROM quizzes
ORDER BY topic_key;



-- ============================================================
-- [TEST] Create anonymous learner
-- Backend should do this automatically via session_id
-- ============================================================
INSERT INTO learners (session_id)
VALUES (gen_random_uuid())
RETURNING learner_id, session_id;



-- ============================================================
-- [TEST] Get quiz ID for intro topic
-- ============================================================
SELECT quiz_id FROM quizzes WHERE topic_key = 'intro';



-- ============================================================
-- [TEST] Create quiz attempt (example)
-- ============================================================
INSERT INTO quiz_attempts (learner_id, quiz_id)
VALUES (
  'edb0212d-1089-454a-bae9-aa42770f60ec',
  'cf28a496-5633-4fe9-ac9f-3f1ffe696c7f'
)
RETURNING attempt_id;



-- ============================================================
-- [TEST] Submit quiz attempt with score
-- ============================================================
UPDATE quiz_attempts
SET
  submitted_at = now(),
  score_percent = 80,
  is_passed = TRUE
WHERE attempt_id = 'e41f14b2-0232-4c81-88c8-7d49793abdad';



SELECT * FROM quiz_attempts;



-- ============================================================
-- [TEST] Update topic progress for intro
-- ============================================================
UPDATE topic_progress
SET
  best_score_percent = GREATEST(best_score_percent, 80),
  is_completed = TRUE,
  completed_at = now()
WHERE learner_id = 'edb0212d-1089-454a-bae9-aa42770f60ec'
  AND topic_key = 'intro';



INSERT INTO topic_progress (
  learner_id,
  topic_key,
  best_score_percent,
  is_completed,
  completed_at
)
VALUES (
  'edb0212d-1089-454a-bae9-aa42770f60ec',
  'intro',
  80,
  TRUE,
  now()
);



SELECT * FROM topic_progress;



-- ============================================================
-- Add updated_at column (optional enhancement)
-- ============================================================
ALTER TABLE topic_progress
ADD COLUMN updated_at TIMESTAMPTZ DEFAULT now();



-- ============================================================
-- [TEST] Mark all topics completed (certificate test)
-- ============================================================
INSERT INTO topic_progress (
  learner_id,
  topic_key,
  best_score_percent,
  is_completed,
  completed_at
)
SELECT
  'edb0212d-1089-454a-bae9-aa42770f60ec',
  topic_key,
  75,
  TRUE,
  now()
FROM topics
ON CONFLICT (learner_id, topic_key) DO NOTHING;



SELECT topic_key, best_score_percent, is_completed
FROM topic_progress
ORDER BY topic_key;



-- ============================================================
-- [CERTIFICATION CHECK]
-- Learner is eligible if completed topic count == total topics
-- ============================================================
SELECT
  COUNT(*) = (
    SELECT COUNT(*) FROM topics WHERE is_active = TRUE
  ) AS eligible
FROM topic_progress
WHERE learner_id = 'edb0212d-1089-454a-bae9-aa42770f60ec'
  AND is_completed = TRUE;



-- ============================================================
-- [CERTIFICATE ISSUANCE]
-- ============================================================
INSERT INTO certificates (
  learner_id,
  certificate_code,
  completed_topics
)
SELECT
  'edb0212d-1089-454a-bae9-aa42770f60ec',
  'LCSS-' || UPPER(SUBSTRING(gen_random_uuid()::text, 1, 8)),
  jsonb_agg(topic_key)
FROM topic_progress
WHERE learner_id = 'edb0212d-1089-454a-bae9-aa42770f60ec'
  AND is_completed = TRUE;



SELECT * FROM certificates;
SELECT * FROM topic_progress ORDER BY topic_key;
SELECT * FROM quiz_attempts;
SELECT * FROM learners;



-- ============================================================
-- Prevent issuing more than one certificate per learner
-- ============================================================
CREATE UNIQUE INDEX IF NOT EXISTS uq_one_certificate_per_learner
ON certificates (learner_id);



SELECT * FROM certificates ORDER BY issued_at DESC;
